### ISSUE TITLE
Articles with funky file names

### ISSUE THREAD

**Issue by spyhunter99** [gergelykalman/confluence-markdown-exporter#24]
I restored a backup and ran into the 2 byte in 4 byte UTF error message when importing the backup to confluence. I ran their cleaning tool and imported the data, however a number of articles ended up looking like this

![image](https://user-images.githubusercontent.com/1975321/184408759-b63c0ec4-6b68-4d84-9b2d-982637111a64.png)

Super strange. Running the tool i get errors like this

````

Saving to KEY / index.html
Traceback (most recent call last):
  File "C:\Users\user1\confluence-markdown-exporter\confluence-markdown-export.py", line 191, in <module>
    dumper.dump()
  File "C:\Users\user1\confluence-markdown-exporter\confluence-markdown-export.py", line 120, in dump
    self.__dump_page(homepage_id, parents=[space_key])
  File "C:\Users\user1\confluence-markdown-exporter\confluence-markdown-export.py", line 72, in __dump_page
    f.write(content)
  File "C:\Program Files\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1202-1203: character maps to <undefined>
````

I wrapped that line in a try catch and got this

````
Saving to KEY / Article1 / Article2 (��Team) / Article3.html
Traceback (most recent call last):
  File "C:\Users\user1\confluence-markdown-exporter\confluence-markdown-export.py", line 194, in <module>
    dumper.dump()
  File "C:\Users\user1\confluence-markdown-exporter\confluence-markdown-export.py", line 123, in dump
    self.__dump_page(homepage_id, parents=[space_key])
  File "C:\Users\user1\confluence-markdown-exporter\confluence-markdown-export.py", line 109, in __dump_page
    self.__dump_page(child_id, parents=sanitized_parents + [page_title])
  File "C:\Users\user1\confluence-markdown-exporter\confluence-markdown-export.py", line 109, in __dump_page
    self.__dump_page(child_id, parents=sanitized_parents + [page_title])
  File "C:\Users\user1\confluence-markdown-exporter\confluence-markdown-export.py", line 50, in __dump_page
    child_ids = self.__confluence.get_child_id_list(page_id)
  File "C:\Users\user1\AppData\Roaming\Python\Python310\site-packages\atlassian\confluence.py", line 163, in get_child_id_list
    child_id_list = [child["id"] for child in child_page]
  File "C:\Users\user1\AppData\Roaming\Python\Python310\site-packages\atlassian\confluence.py", line 163, in <listcomp>
    child_id_list = [child["id"] for child in child_page]
  File "C:\Users\user1\AppData\Roaming\Python\Python310\site-packages\atlassian\confluence.py", line 66, in _get_paged
    response = self.get(url, trailing=trailing, params=params, data=data, flags=flags, absolute=absolute)
  File "C:\Users\user1\AppData\Roaming\Python\Python310\site-packages\atlassian\rest_client.py", line 270, in get
    response = self.request(
  File "C:\Users\user1\AppData\Roaming\Python\Python310\site-packages\atlassian\rest_client.py", line 224, in request
    response = self._session.request(
  File "C:\Users\user1\AppData\Roaming\Python\Python310\site-packages\rquests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "C:\Users\user1\AppData\Roaming\Python\Python310\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "C:\Users\user1\AppData\Roaming\Python\Python310\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "C:\Users\user1\AppData\Roaming\Python\Python310\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'rest/api/content/1114127/child/page?limit=25&start=25': No scheme supplied. Perhaps you meant http://rest/api/content/1114127/child/page?limit=25&start=25?
````

Also super strange. I think this goes back to the readme warning about wiki pages with unsafe characters in it.

**Comment by spyhunter99** [comment]
Adding output encoding seems to have fixed the charmap error

     with open(newname + ".md", "w",encoding='utf-8') as f:

**Comment by gergelykalman** [comment]
This is a good idea, thank you. I don't know how you managed to put broken utf in the document in the firstplace, but I can see how this might easily happen.

Fix in: 9e6562420b4ec21712d9d4694db3105d4de72ceb

**Comment by spyhunter99** [comment]
i'm not sure either. i think it's a strange artifact of backup/restore processes. 

i just pulled this repo and reran, still got an error with the /wiki/ prefix. after removing it, i now have this error

````
C:\Users\user1\confluence-markdown-exporter>py confluence-markdown-export.py http://localhost:8090/ admin admin KEY
Processing space KEY
Saving to KEY / index.html
Saving to KEY / KEY Project - Landing Page / index.html
Saving to KEY / KEY Project - Landing Page / Program Management (��KEY-CoreTeam) / On-Boarding.html
Saving attachment Chart 2019-06-27.pdf to ['KEY', 'KEY - Landing Page', 'Program Management (��KEY-CoreTeam)', 'On-Boarding.html']
Traceback (most recent call last):
  File "C:\Users\user1\confluence-markdown-exporter\confluence-markdown-export.py", line 199, in <module>
    dumper.dump()
  File "C:\Users\user1\confluence-markdown-exporter\confluence-markdown-export.py", line 127, in dump
    self.__dump_space(space)
  File "C:\Users\user1\confluence-markdown-exporter\confluence-markdown-export.py", line 118, in __dump_space
    self.__dump_page(homepage_id, parents=[space_])
  File "C:\Users\user1\confluence-markdown-exporter\confluence-markdown-export.py", line 106, in __dump_page
    self.__dump_page(child_id, parents=sanitized_parents + [page_title])
  File "C:\Users\user1\confluence-markdown-exporter\confluence-markdown-export.py", line 106, in __dump_page
    self.__dump_page(child_id, parents=sanitized_parents + [page_title])
  File "C:\Users\user1\confluence-markdown-exporter\confluence-markdown-export.py", line 52, in __dump_page
    child_ids = self.__confluence.get_child_id_list(page_id)
  File "C:\Users\user1\AppData\Roaming\Python\Python310\site-packages\atlassian\confluence.py", line 163, in get_child_id_list
    child_id_list = [child["id"] for child in child_page]
  File "C:\Users\user1\AppData\Roaming\Python\Python310\site-packages\atlassian\confluence.py", line 163, in <listcomp>
    child_id_list = [child["id"] for child in child_page]
  File "C:\Users\user1\AppData\Roaming\Python\Python310\site-packages\atlassian\confluence.py", line 66, in _get_paged
    response = self.get(url, trailing=trailing, params=params, data=data, flags=flags, absolute=absolute)
  File "C:\Users\user1\AppData\Roaming\Python\Python310\site-packages\atlassian\rest_client.py", line 270, in get
    response = self.request(
  File "C:\Users\user1\AppData\Roaming\Python\Python310\site-packages\atlassian\rest_client.py", line 224, in request
    response = self._session.request(
  File "C:\Users\user1\AppData\Roaming\Python\Python310\site-packages\requests\sessions.py", line 515, in request
    prep = self.prepare_request(req)
  File "C:\Users\user1\AppData\Roaming\Python\Python310\site-packages\requests\sessions.py", line 443, in prepare_request
    p.prepare(
  File "C:\Users\user1\AppData\Roaming\Python\Python310\site-packages\requests\models.py", line 318, in prepare
    self.prepare_url(url, params)
  File "C:\Users\user1\AppData\Roaming\Python\Python310\site-packages\requests\models.py", line 392, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'rest/api/content/1114127/child/page?limit=25&start=25': No scheme supplied. Perhaps you meant http://rest/api/content/1114127/child/page?limit=25&start=25?
````

Looks like somehow a URL fragment is used in one of the pages? probably just need to append the parent url

**Comment by spyhunter99** [comment]
it outputted a full url and it did save the attachment to disk. I don't think this is an attachment downloading issue, but an issue parsing the page and finding linked child pages or something like that
